// src/app/layout.tsx
import type { Metadata } from "next";
import "@/styles/globals.css";

import { Providers } from "@/app/providers";
import { ScrollToTop } from "@/components";

import localFont from "next/font/local";
import { Bai_Jamjuree } from "next/font/google";

const lineSeedSans = localFont({
  src: [
    { path: "../styles/fonts/LINESeedSansTH_W_Th.woff", weight: "100" }, // Thin
    { path: "../styles/fonts/LINESeedSansTH_W_Rg.woff", weight: "400" }, // Regular
    { path: "../styles/fonts/LINESeedSansTH_W_Bd.woff", weight: "700" }, // Bold
    { path: "../styles/fonts/LINESeedSansTH_W_XBd.woff", weight: "800" }, // Extra Bold
    { path: "../styles/fonts/LINESeedSansTH_W_He.woff", weight: "900" }, // Heavy
  ],
  variable: "--font-line-seed-sans",
});

const baiJamjuree = Bai_Jamjuree({
  subsets: ["latin"],
  weight: ["400", "600"], // Regular & SemiBold
  variable: "--font-bai-jamjuree",
})

export const metadata: Metadata = {
  title: "Bangkrachao",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th" className="light">
      <body className={`${lineSeedSans.variable} ${baiJamjuree.variable} antialiased`} >
        <Providers>
          <div className="min-h-screen flex flex-col">
            <main className="flex-grow">
              {children}
            </main>
          </div>
          <ScrollToTop/>
        </Providers>
      </body>
    </html>
  );
}